### ISSUE TITLE
P-Value is Either 1 or 0

### ISSUE THREAD

**Issue by ayushboss** [stamfest/randomtests#1]
Hi there!

I have been using your implementations of the NIST Suite algorithms to test the basic Math.random java function. Unfortunately, the p-value is always either 0 or 1 (0 for failure, 1 for success). I wanted to know if this is the intended effect, and if not then how to combat this issue.

Thank you!
Ayush

**Comment by ayushboss** [comment]
Note: my data is a stream cipher, meaning that all values being tested are either 0 or 1

**Comment by stamfest** [comment]
I didn't see this issue for well over a year, sorry for this. I guess you no longer have the problem :-) For others: It *may* be an issue with the input data format...

**Comment by ayushboss** [comment]
Hi there, I wasn't ever able to fix the issue with this set and instead moved to working on the base code provided by NIST themselves. However, it may have been an issue with the input data format, I don't remember too clearly. Hopefully nobody else faces this issue!

**Comment by stamfest** [comment]
It likely was: I really tried hard to make this as compatible to the original NIST code as possible and feeding single bits thus is special here *and* there, AFAIR. The "bits" package was designed to address this issue if used programmatically from other code. The "--inform" option of the Assess tool addresses the issue with input data from a file.
